- name: Update dotfiles on local PVE server, router and VMs/LXCs
  hosts: updatedfall
  tasks:
    - name: Run upgradedotfiles.sh script on remote services hosts
      ansible.builtin.shell: cd "${HOME}/dotfiles/common/ansible/clientscripts" && ./updatedotfiles.sh
      register: out

    - debug: var=out.stdout_lines
